# Generated by Django 3.2.7 on 2021-09-05 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='articles',
            name='mail',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Почта'),
            preserve_default=False,
        ),
    ]
